---
apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: default
spec:
  type: NodePort
  selector:
    app: garage
  ports:
    - name: s3
      port: 3900
      targetPort: 3900
      nodePort: {{ .Values.nodePorts.s3 }}
    - name: admin
      port: 3902
      targetPort: 3902
      nodePort: {{ .Values.nodePorts.admin }}
