apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stackable-cockpit.fullname" . }}
  labels:
    {{- include "stackable-cockpit.labels" . | nindent 4 }}
data:
  base-url: {{ .Values.auth.baseUrl | quote }}
  {{- with .Values.origin }}
  origin: {{ . | quote }}
  {{- end }}
  {{- if .Values.auth.oidc.enabled }}
  oidc-discovery-url: {{ required "auth.oidc.discoveryUrl is required when OIDC is enabled" .Values.auth.oidc.discoveryUrl | quote }}
  oidc-client-id: {{ required "auth.oidc.clientId is required when OIDC is enabled" .Values.auth.oidc.clientId | quote }}
  {{- end }}
  {{- with .Values.trino.url }}
  trino-url: {{ . | quote }}
  {{- end }}
  {{- with .Values.trino.auth.type }}
  trino-auth-type: {{ . | quote }}
  {{- end }}
  {{- with .Values.trino.auth.username }}
  trino-auth-username: {{ . | quote }}
  {{- end }}
