{{- if not .Values.sessionSecret.secretKeyRef.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackable-cockpit.fullname" . }}
  labels:
    {{- include "stackable-cockpit.labels" . | nindent 4 }}
type: Opaque
stringData:
  session-secret: {{ include "stackable-cockpit.sessionSecret" . | quote }}
{{- end }}
