apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackable-cockpit.fullname" . }}
  labels:
    {{- include "stackable-cockpit.labels" . | nindent 4 }}
type: Opaque
stringData:
  session-secret: {{ include "stackable-cockpit.sessionSecret" . | quote }}
  oidc-client-secret: {{ .Values.auth.clientSecret | quote }}
  {{- if .Values.trino.authPassword }}
  trino-auth-password: {{ .Values.trino.authPassword | quote }}
  {{- end }}
