---
image:
  repository: postgres
  tag: '18.4-alpine3.23'
  pullPolicy: IfNotPresent

# Database configuration
database:
  name: cockpit
  user: cockpit
  password: cockpit-dev-password

# NodePort value for host access.
# PostgreSQL is exposed on nodePorts.postgres
nodePorts:
  postgres: 31432
