apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stackable-ui.fullname" . }}
  labels:
    {{- include "stackable-ui.labels" . | nindent 4 }}
data:
  oidc-discovery-url: {{ .Values.auth.discoveryUrl | quote }}
  oidc-client-id: {{ .Values.auth.clientId | quote }}
  base-url: {{ .Values.auth.baseUrl | quote }}
  {{- with .Values.origin }}
  origin: {{ . | quote }}
  {{- end }}
  {{- if .Values.trino.url }}
  trino-url: {{ .Values.trino.url | quote }}
  {{- end }}
  {{- if .Values.trino.authType }}
  trino-auth-type: {{ .Values.trino.authType | quote }}
  {{- end }}
  {{- if .Values.trino.authUsername }}
  trino-auth-username: {{ .Values.trino.authUsername | quote }}
  {{- end }}
