apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackable-ui.fullname" . }}
  labels:
    {{- include "stackable-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  session-secret: {{ include "stackable-ui.sessionSecret" . | quote }}
