---
image:
  repository: oci.stackable.tech/stackable/dxflrs/garage
  tag: v2.3.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

ingress:
  enabled: true
  className: traefik
  host: garage.localhost
  tls:
    secretName: local-dev-tls
