# shellcheck shell=bash
env::write() {
  log::info "Writing .env.development..."

  local session_secret encryption_key
  session_secret=$(openssl rand -hex 32)
  encryption_key=$(openssl rand -hex 32)

  if [ -f "$ENV_FILE" ]; then
    log::info "Backing up existing .env.development to .env.development.bak"
    cp "$ENV_FILE" "$ENV_FILE.bak"
  fi

  if [[ "$SKIP_TRINO" == false ]]; then
    cat > "$ENV_FILE" <<EOF
STACKABLE_COCKPIT_OIDC_DISCOVERY_URL=${KEYCLOAK_BASE_URL}/realms/stackable/.well-known/openid-configuration
STACKABLE_COCKPIT_OIDC_CLIENT_ID=stackable-cockpit
STACKABLE_COCKPIT_OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
STACKABLE_COCKPIT_SESSION_SECRET=${session_secret}
STACKABLE_COCKPIT_BASE_URL=http://localhost:5173
STACKABLE_COCKPIT_TRINO_URL=${TRINO_BASE_URL}
STACKABLE_COCKPIT_TRINO_AUTH_TYPE=basic
STACKABLE_COCKPIT_TRINO_AUTH_USERNAME=stackable-cockpit
STACKABLE_COCKPIT_TRINO_AUTH_PASSWORD=stackable-cockpit-dev
STACKABLE_COCKPIT_TRINO_TLS_INSECURE=true
STORAGE_ENCRYPTION_KEY=${encryption_key}
STACKABLE_COCKPIT_STORAGE_BROWSER_ENABLED=true
STACKABLE_COCKPIT_TEXT_PREVIEW_BYTES=262144
STACKABLE_COCKPIT_IMAGE_PREVIEW_BYTES=5242880
STACKABLE_COCKPIT_PDF_PREVIEW_BYTES=26214400
STACKABLE_COCKPIT_FILE_PREVIEW_ROWS=250
STACKABLE_COCKPIT_ARCHIVE_PREVIEW_MAX_MB=100
STACKABLE_COCKPIT_PARQUET_PREVIEW_DISALLOWED_COMPRESSION_TYPES=gzip-no_offset
PUBLIC_STACKABLE_COCKPIT_STORAGE_AUTO_CONNECT=true
PUBLIC_STACKABLE_COCKPIT_STORAGE_RESTORE_TABS=true
PUBLIC_STACKABLE_COCKPIT_PAGE_SIZES=25,50,100
PUBLIC_STACKABLE_COCKPIT_DEFAULT_PAGE_SIZE=25
PUBLIC_STACKABLE_COCKPIT_MAX_RECENT_FILES=15
PUBLIC_STACKABLE_COCKPIT_STORAGE_AUTO_CONNECT_TIMEOUT_MS=15000
PUBLIC_STACKABLE_COCKPIT_MAX_EDITABLE_FILE_SIZE=5242880
PUBLIC_STACKABLE_COCKPIT_UPLOAD_CONCURRENCY=3
PUBLIC_STACKABLE_COCKPIT_INFINITE_SCROLL_ENABLED=true
PUBLIC_STACKABLE_COCKPIT_STORAGE_CUT_COPY_ENABLED=true
PUBLIC_STACKABLE_COCKPIT_STORAGE_PASTE_ENABLED=true
PUBLIC_STACKABLE_COCKPIT_STORAGE_RENAME_ENABLED=true
PUBLIC_STACKABLE_COCKPIT_STORAGE_MOVE_ENABLED=true
DATABASE_HOST=localhost
DATABASE_PORT=31432
DATABASE_NAME=cockpit
DATABASE_USER=cockpit
DATABASE_PASSWORD=cockpit-dev-password
EOF
  else
    cat > "$ENV_FILE" <<EOF
STACKABLE_COCKPIT_OIDC_DISCOVERY_URL=${KEYCLOAK_BASE_URL}/realms/stackable/.well-known/openid-configuration
STACKABLE_COCKPIT_OIDC_CLIENT_ID=stackable-cockpit
STACKABLE_COCKPIT_OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
STACKABLE_COCKPIT_SESSION_SECRET=${session_secret}
STACKABLE_COCKPIT_BASE_URL=http://localhost:5173
STORAGE_ENCRYPTION_KEY=${encryption_key}
STACKABLE_COCKPIT_STORAGE_BROWSER_ENABLED=true
STACKABLE_COCKPIT_TEXT_PREVIEW_BYTES=262144
STACKABLE_COCKPIT_IMAGE_PREVIEW_BYTES=5242880
STACKABLE_COCKPIT_PDF_PREVIEW_BYTES=26214400
STACKABLE_COCKPIT_FILE_PREVIEW_ROWS=250
STACKABLE_COCKPIT_PARQUET_PREVIEW_DISALLOWED_COMPRESSION_TYPES=gzip-no_offset
PUBLIC_STACKABLE_COCKPIT_STORAGE_AUTO_CONNECT=true
PUBLIC_STACKABLE_COCKPIT_STORAGE_RESTORE_TABS=true
PUBLIC_STACKABLE_COCKPIT_PAGE_SIZES=25,50,100
PUBLIC_STACKABLE_COCKPIT_DEFAULT_PAGE_SIZE=25
PUBLIC_STACKABLE_COCKPIT_MAX_RECENT_FILES=15
PUBLIC_STACKABLE_COCKPIT_STORAGE_AUTO_CONNECT_TIMEOUT_MS=15000
PUBLIC_STACKABLE_COCKPIT_MAX_EDITABLE_FILE_SIZE=5242880
PUBLIC_STACKABLE_COCKPIT_UPLOAD_CONCURRENCY=3
PUBLIC_STACKABLE_COCKPIT_INFINITE_SCROLL_ENABLED=true
PUBLIC_STACKABLE_COCKPIT_STORAGE_CUT_COPY_ENABLED=true
PUBLIC_STACKABLE_COCKPIT_STORAGE_PASTE_ENABLED=true
PUBLIC_STACKABLE_COCKPIT_STORAGE_RENAME_ENABLED=true
PUBLIC_STACKABLE_COCKPIT_STORAGE_MOVE_ENABLED=true
DATABASE_HOST=localhost
DATABASE_PORT=31432
DATABASE_NAME=cockpit
DATABASE_USER=cockpit
DATABASE_PASSWORD=cockpit-dev-password
EOF
  fi

  log::ok "Wrote $ENV_FILE"
}
