---
image:
  registry: ''
  repository: stackable-cockpit
  tag: local
  pullPolicy: Never

auth:
  baseUrl: 'https://cockpit.localhost'
  oidc:
    enabled: false

origin: 'https://cockpit.localhost'

proxy:
  protocolHeader: x-forwarded-proto
  hostHeader: x-forwarded-host

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: cockpit.localhost
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: local-dev-tls
      hosts:
        - cockpit.localhost

features:
  storage:
    enabled: true
    autoConnect: true
